spring:
  application:
    name: syncup-backend

  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres
    username: "postgres.cteobhqgjxocepuksnxw"
    password: _RS2*7P$#Aq&Wfb
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update