spring:
  application:
    name: syncup-backend

  datasource:
    url: jdbc:postgresql://db.cteobhqgjxocepuksnxw.supabase.co:5432/postgres
    username: "postgres"
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
